[shell]
program = "/home/spiritum/.cargo/bin/zellij"

[terminal]
osc52 = "CopyPaste"

#[keyboard]
#bindings = [
#{ key = "C", mods = "Control|Shift", action = "Copy" },
#{ key = "V", mods = "Control|Shift", action = "Paste" },
#]
